# Generated by Django 4.2.1 on 2023-06-20 19:47

from django.db import migrations, models

def status_cart(apps, schema_editor):    
    
    types = ["Новый", "Принят", "В обработке", "Завершен", "Отменен"]
    # Попросим Django вытащить модель - класс Status из аппликейшена order
    Status = apps.get_model("order", "Status")
    
    #Теперь в цикле создаём экземпляры класса с указанными параметрами и сохраняем их 
    for t in types:
        st_type = Status(name=t)
        st_type.save()

class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(status_cart)
    ]
