# Generated by Django 4.2.1 on 2023-06-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20230620_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='Новый', on_delete=django.db.models.deletion.PROTECT, to='order.status', verbose_name='Статус заказа'),
        ),
    ]
