# Generated by Django 4.2.1 on 2023-06-20 20:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_created_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
