# Generated by Django 4.2.1 on 2023-06-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_name_alter_type_name_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='type',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_rn', to='category.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание типа'),
        ),
    ]
