# Generated by Django 4.2.1 on 2023-06-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_category_description_alter_type_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='pls add type name', max_length=100, verbose_name='Название типа'),
        ),
    ]
