# Generated by Django 4.2.1 on 2023-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='upload/%y/%m/%d', verbose_name='Картинка категории'),
        ),
        migrations.AddField(
            model_name='type',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='upload/%y/%m/%d', verbose_name='Картинка типа'),
        ),
    ]
