# Generated by Django 4.2.1 on 2023-06-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_alter_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d', verbose_name='Картинка категории'),
        ),
        migrations.AlterField(
            model_name='type',
            name='picture',
            field=models.ImageField(default='', upload_to='uploads/%Y/%m/%d', verbose_name='Картинка категории'),
            preserve_default=False,
        ),
    ]
