# Generated by Django 4.2.1 on 2023-06-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0012_alter_category_picture_alter_type_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название товара', max_length=150, verbose_name='Название товара')),
                ('item_number', models.CharField(db_index=True, max_length=50, verbose_name='Артикул')),
                ('picture', models.ImageField(upload_to='uploads/%Y/%m/%d', verbose_name='Изображение товара')),
                ('description', models.TextField(blank=True, help_text='Введите описание товара', null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна производителя')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Бренд')),
                ('enable', models.BooleanField(default=False, verbose_name='Видимость')),
                ('count', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('search_terms', models.CharField(blank=True, max_length=500, null=True, verbose_name='Поисковые запросы')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка в %')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания товара')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_rev', to='category.category', verbose_name='Категория товара')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_rev', to='category.type', verbose_name='Тип товара')),
            ],
        ),
    ]
