# Generated by Django 4.2.1 on 2023-05-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='City name')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='City discription')),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Holiday name')),
                ('date_holiday', models.DateField(verbose_name='holiday date')),
                ('duration', models.IntegerField(default=1, verbose_name='holiday duration')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Public Holiday discription')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='When add holiday')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='When update holiday')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='День недели')),
                ('work_time', models.TimeField(default='09:00', verbose_name='Начало рабочего дня')),
                ('work_end', models.TimeField(default='18:00', verbose_name='Конец рабочего дня')),
            ],
        ),
    ]
